theme: auto

server:
  address: tcp://0.0.0.0:9091

log:
  level: info

identity_validation:
  reset_password:
    jwt_lifespan: 5 minutes

authentication_backend:
  file:
    path: /config/users_database.yml
    watch: true
    search:
      email: true
      case_insensitive: true

access_control:
  default_policy: deny
  rules:
    - domain: logs.jackharrhy.dev
      policy: one_factor
      subject:
        - group:admins

session:
  cookies:
    - domain: jackharrhy.dev
      authelia_url: https://auth.jackharrhy.dev
      default_redirection_url: https://logs.jackharrhy.dev
      same_site: lax
      inactivity: 1 hour
      expiration: 8 hours
      remember_me: 30 days

storage:
  local:
    path: /data/db.sqlite3

notifier:
  filesystem:
    filename: /data/notifications.txt
