DO_AUTH_TOKEN: ENC[AES256_GCM,data:hLzN4VaNukxZUxP7OKPIKrxQu4JbUx23I2MwDpPFYJD/PDQ6JDxfDshjOENnzeCu3YISrQNIS7hnZnhiadgoiZqmA1ztJSo=,iv:+piPpIUtnRJI9JZPBWmDfv/wEds1EAHc7Cc6hXScSiE=,tag:CUH/jja9K0YUSComJU0i4w==,type:str]
sops:
    age:
        - recipient: age1pxvmxa7pqmaxsxhhe7d9rfs2glaqtzxkpkmhz5lzkcalrgtpzp2s4ap0uu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWRVpHK3NFVjBhNmhBVHpT
            WnpnTUl1bjBIeE0vbFRVS1lLQldTT2V6UkRFCmtQeG5mVkM2ZS9PZjdRUjR1UUdl
            SGo3Zzk1TUZlZ2daOXlZVEJyNlNyWVUKLS0tIDExMVZlRWZhVW16Ni80Y1ZYYVgx
            U2JaWlZvd2wxWjBpajArYWNkYXJEVk0KGTM9F5EabJW5gkSfw2YLKYyvITkeUDLS
            CTH1UX/hPKApWHkR6Rdc56VokIhW5tNwDh/MEc9EJrhr2uADPW5pgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T00:47:00Z"
    mac: ENC[AES256_GCM,data:VKWa9FueazU4Pk9M2F9qUqWvgIXNHav9tYTeCGHHPgpX9tNj08sIVFBNex0MbHKMnW5SdZWldNx6Uu2gBzJ9KjMJR1MIAf63HMagVZj+m21zf2KD9IWceZxfAZyhAbRM6mRpUw9N3ulCshWjhJpUvTICFtOSsgR9AaI89/SIsis=,iv:76d/ezhGjmv4G2aGRiGMqlYDpGmmXNbWsfcxIPJk3wQ=,tag:q/2lYhZ+CTqehNv6NqpbhQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
