server {
    listen 80;
    server_name _;
    root /srv;
    add_header X-Content-Type-Options nosniff always;

    location /uploads/ {
        limit_except GET HEAD { deny all; }
        try_files $uri =404;
        expires 1d;
    }

    location / {
        return 301 https://andrewgossecomposer.com/tea/admin;
    }
}
