CF_DNS_API_TOKEN: ENC[AES256_GCM,data:R0n2VrMkfO9cPBJkplIVOyRyv43w+SKZRB+voKTDQXRWFoZQ58q+ps9yq5KpFoVhurVuQ2s=,iv:OOyecb7we22TUh5xS9WQBHbJFuiz6H8fvLjTkWaGkJI=,tag:7WebJt+35WVSY1WuI+FwAA==,type:str]
sops:
    age:
        - recipient: age1pxvmxa7pqmaxsxhhe7d9rfs2glaqtzxkpkmhz5lzkcalrgtpzp2s4ap0uu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSHNrOVdtR3lZYWVKSThw
            TS9sOUN0K0NOY2E1aW5HeVZZVUlGL1A0VlFFCnFCUGpWTVRNZDBUcSt1bUtsL3dK
            TVdRRjdLRzZDc2lLVzNOUHhGc2pSRFkKLS0tIG9GcDRYQUxCZWUrZm1zb1ZZajdL
            V2N3cFJseFlTd0hqdGdmbWtqa2lKMDAKaLIrBFhEfJluI7GyK0tqvNUJ/5q+E+4S
            if6bVpKvWq9hMixa1LcW1GRtChJGxm6dOoSF8HqxNkBM4A52XDEMOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-12T23:01:22Z"
    mac: ENC[AES256_GCM,data:7Gq753f4Xh4ufSexsVGEgSfZ1p6D5vjWuVWgEI3HW13RKMHrUggKhhqrYhUb9vZusA4wlUELn+MeccIvHKwM+EKwtkk6Nj5r+4kV2NWeuL1iClkXqst3X7UPn4dj07gHE+Sbo2qhs1d0QXfU5gfhdoIgXs4FXXJnOQCriRtA6lY=,iv:K1VZwRUxUS1ZqdBHbrfAQF35mmCD4g3X5If6jWKOd4g=,tag:qrLwdtyOkGHZX1kWobf3tg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
