name: default
permissions:
  - essentials.*:
      value: false
  - essentials.spawn:
      value: false
  - proantitab.bypass:
      value: false
  - proantitab.namespace:
      value: false
  - proantitab.use:
      value: false
  - essentials.msg
  - essentials.msg.url
  - essentials.r
  - essentials.back.onteleport:
      value: false
  - essentials.motd:
      value: false
  - bukkit.command.plugins:
      value: false
  - bukkit.command.version:
      value: false
  - bukkit.command.help:
      value: false
  - minecraft.command.help:
      value: false
  - bukkit.command.about:
      value: false
  - gsit.playersit:
      value: false
  - gsit.playersittoggle:
      value: false
  - discordsrv.*:
      value: false
  - imageframe.info:
      value: false
  - imageframe.list:
      value: false
  - imageframe.preference:
      value: false
  - emf.help:
      value: false
  - emf.shop:
      value: false
  - emf.sellall:
      value: false
  - voicechat.listen
  - voicechat.speak
  - voicechat.groups:
      value: false
  - interactionvisualizer.toggle
  - interactionvisualizer.refresh:
      value: false
  - gsit.*:
      value: false
  - gsit.pose.*:
      value: false
  - gsit.crawl.*:
      value: false
  - gsit.lay:
      value: false
  - gsit.layback:
      value: false
  - gsit.bellyflop:
      value: false
  - gsit.spin:
      value: false
  - gsit.crawl:
      value: false
  - gsit.crawlsneak:
      value: false
  - gsit.crawltoggle:
      value: false
  - gsit.sit
  - gsit.sitclick
  - gsit.sittoggle
  - imageframe.create.animated:
      value: false
