services:
  beancraft:
    image: itzg/minecraft-server:java21
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    env_file:
      - ./.runtime-secrets/beancraft.env
    environment:
      EULA: "true"
      TYPE: "AUTO_CURSEFORGE"
      CF_PAGE_URL: "https://www.curseforge.com/minecraft/modpacks/all-of-create-aeronautics"
      MEMORY: "12G"
      USE_AIKAR_FLAGS: "true"
      MOTD: "beancraft"
      OPS: cheesemany
      WHITELIST: cheesemany
      CF_FORCE_INCLUDE_MODS: "bluemap"
    volumes:
      - ./data:/data
    networks:
      - web
    labels:
      - "traefik.docker.network=newport_web"
      - "traefik.enable=true"
      - "traefik.http.services.beancraft.loadbalancer.server.port=8100"
      - "traefik.http.routers.beancraft.rule=Host(`craft.jackharrhy.dev`)"
      - "traefik.http.routers.beancraft.entrypoints=web"

networks:
  web:
    external: true
    name: newport_web
