verboseLogging: false
port: 7001
URL: "http://10.0.0.80:7001/"
postConfigResponse: postHopperConfig
initialPageResponse: HopperConfig
editPageResponse: editHopperConfig
postEditPageResponse: postEditHopperConfig
maxInputItems: 100
disabledItems:
  - spawn_egg
