verboseLogging: false
port: 7001
URL: "https://cheesetown.rocks/item-sorter/"
postConfigResponse: postHopperConfig
initialPageResponse: HopperConfig
editPageResponse: editHopperConfig
postEditPageResponse: postEditHopperConfig
maxInputItems: 100
disabledItems:
  - spawn_egg
