direction: down

tailscale: Tailscale {
  shape: cloud
}

digitalocean: DigitalOcean {
  mug: "mug (1 cores / 2GB / 50GB disk)" {
    infra: Infrastructure {
      grid-columns: 1
      traefik: traefik
      watchtower: watchtower
      beszel: beszel
      beszel-agent: beszel-agent
    }

    websites: Websites {
      grid-columns: 2
      easter_egg: 142.93.144.29
      easter_egg.tooltip: 142.93.144.29, 2604:a880:cad:d0::dff:a001
      jackharrhy: jackharrhy.dev
      jackharrhy.tooltip: jackharrhy.dev, jackharrhy.com, harrhy.xyz, jack.harrhy.xyz, jack.arthur.harrhy.xyz, jack.is.harrhy.xyz
      siliconharbour: siliconharbour.dev
      plow: plow.jackharrhy.dev
      burger: big.burger.beauty
      andrewsite_astro: andrewgossecomposer.com
      andrewsite_strapi: api.andrewgossecomposer.com
      stackcoin: stackcoin.world
      luckypot: luckypot
      lists: lists.jackharrhy.dev
      zonia: zonia.harrhy.xyz
      gurgur: gurgur.rotund.org
    }

    bots: Bots & Workers {
      grid-columns: 2
      quak: quak
    }

  }

}

home: Home {
  newport: "newport (12 cores / 64GB / 100GB disk)" {
    infra: Infrastructure {
      grid-columns: 1
      traefik: traefik
      watchtower: watchtower
      beszel-agent: beszel-agent
    }

    websites: Websites {
      grid-columns: 2
      "4orm": 4orm.harrhy.xyz
      adam_eats: adam-eats.jackharrhy.dev
      artbin: artbin.jackharrhy.dev
      rotund_org: rotund.org
      stickertrade: stickertrade.ca
      sluggers_super_draft: lil-slug-crew.jackharrhy.dev
      miniflux: miniflux.jackharrhy.dev
      cmd: cmd.softspark.dev
      bar: jackharrhy.dev/bar
      duaas: jackharrhy.dev/urandom
      almanac: almanac.jackharrhy.dev
      marky: marky.jackharrhy.dev
      steve: steve-letter-writ.ing
      notscared_site: notsca.red
      rolie_polie_olie: rolie-polie-olie.fogo.sh
    }

    databases: Databases {
      grid-columns: 1
      sluggers_super_draft_db: sluggers_super_draft_db (postgres:17) {
        shape: cylinder
      }
      miniflux_db: miniflux_db (postgres:15) {
        shape: cylinder
      }
    }

    bots: Bots & Workers {
      grid-columns: 2
      hikeping: hikeping
      cmd_postgres: cmd_postgres
      cmd_garage: cmd_garage
      phapbot: phapbot
      incydecy: incydecy
      house: house
    }

  }

  stash: stash {
    shape: cylinder
  }
}

tailscale -- digitalocean.mug
tailscale -- home

digitalocean.mug.infra.traefik -> home.newport.infra.traefik: proxy

home.newport.websites.sluggers_super_draft -> home.newport.databases.sluggers_super_draft_db
home.newport.websites.miniflux -> home.newport.databases.miniflux_db
