direction: down

tailscale: Tailscale {
  shape: cloud
}

digitalocean: DigitalOcean {
  mug: "mug (1 cores / 2GB / 50GB disk)" {
    infra: Infrastructure {
      grid-columns: 1
      traefik: traefik
      watchtower: watchtower
      beszel: beszel
      beszel-agent: beszel-agent
    }

    websites: Websites {
      grid-columns: 2
      easter_egg: 142.93.144.29
      easter_egg.tooltip: 142.93.144.29, 2604:a880:cad:d0::dff:a001
      jackharrhy: jackharrhy.dev
      jackharrhy.tooltip: jackharrhy.dev, jackharrhy.com, harrhy.xyz, jack.harrhy.xyz, jack.arthur.harrhy.xyz, jack.is.harrhy.xyz
      siliconharbour: siliconharbour.dev
      plow: plow.jackharrhy.dev
      radio-celld: radio.jackharrhy.dev
      burger: big.burger.beauty
      andrewsite_astro: andrewgossecomposer.com
      andrewsite_strapi: api.andrewgossecomposer.com
      stackcoin: stackcoin.world
      luckypot: luckypot
      lists: lists.jackharrhy.dev
      zonia: zonia.harrhy.xyz
      gurgur: gurgur.rotund.org
    }

    bots: Bots & Workers {
      grid-columns: 2
      radio-minio: radio-minio
      radio-minio-bootstrap: radio-minio-bootstrap
      radio-celld-bootstrap: radio-celld-bootstrap
      quak: quak
    }

  }

}

home: Home {
  newport: "newport (12 cores / 64GB / 100GB disk)" {
    infra: Infrastructure {
      grid-columns: 1
      traefik: traefik
      watchtower: watchtower
      beszel-agent: beszel-agent
    }

    websites: Websites {
      grid-columns: 2
      cado: cado.jackharrhy.dev
      "4orm": 4orm.harrhy.xyz
      adam_eats: adam-eats.jackharrhy.dev
      artbin: artbin.jackharrhy.dev
      worldview: worldview.harrhy.xyz
      worldview-azurite: worldview.harrhy.xyz/sync/maps/
      monbooru: monbooru.jackharrhy.dev
      monloader: monloader.jackharrhy.dev
      rotund_org: rotund.org
      stickertrade: stickertrade.ca
      miniflux: miniflux.jackharrhy.dev
      cmd: cmd.softspark.dev
      bar: jackharrhy.dev/bar
      duaas: jackharrhy.dev/urandom
      steve: steve-letter-writ.ing
      notscared_site: notsca.red
      penpot_frontend: penpot.jackharrhy.dev
    }

    databases: Databases {
      grid-columns: 1
      miniflux_db: miniflux_db (postgres:15) {
        shape: cylinder
      }
      penpot_postgres: penpot_postgres (postgres:15) {
        shape: cylinder
      }
    }

    bots: Bots & Workers {
      grid-columns: 2
      worldview-compiler: worldview-compiler
      worldview-celld-bootstrap: worldview-celld-bootstrap
      worldview-celld: worldview-celld
      cmd_postgres: cmd_postgres
      cmd_garage: cmd_garage
      phapbot: phapbot
      incydecy: incydecy
      house: house
      penpot_backend: penpot_backend
      penpot_mcp: penpot_mcp
      penpot_exporter: penpot_exporter
      penpot_valkey: penpot_valkey
    }

  }

  stash: stash {
    shape: cylinder
  }
}

tailscale -- digitalocean.mug
tailscale -- home

digitalocean.mug.infra.traefik -> home.newport.infra.traefik: proxy

home.newport.websites.miniflux -> home.newport.databases.miniflux_db
home.newport.websites.penpot_frontend -> home.newport.databases.penpot_postgres
home.newport.bots.penpot_backend -> home.newport.databases.penpot_postgres
home.newport.bots.penpot_mcp -> home.newport.databases.penpot_postgres
home.newport.bots.penpot_exporter -> home.newport.databases.penpot_postgres
home.newport.bots.penpot_valkey -> home.newport.databases.penpot_postgres
