# Only private messages and spawn; vanilla administration remains available.
ops-name-color: none
change-displayname: false
change-playerlist: false
use-bukkit-permissions: true
player-commands: []
disabled-commands:
- afk
- antioch
- anvil
- back
- backup
- balance
- balancetop
- ban
- banip
- beezooka
- book
- bottom
- break
- broadcast
- broadcastworld
- bigtree
- burn
- cartographytable
- clearinventory
- clearinventoryconfirmtoggle
- condense
- compass
- createkit
- customtext
- delhome
- deljail
- delkit
- delwarp
- depth
- disposal
- eco
- enchant
- enderchest
- exp
- ext
- feed
- fly
- fireball
- firework
- gamemode
- gc
- getpos
- give
- god
- grindstone
- hat
- heal
- help
- helpop
- home
- ice
- ignore
- info
- invsee
- item
- itemdb
- itemlore
- itemname
- jailedplayers
- jails
- jump
- kick
- kickall
- kill
- kit
- kitreset
- kittycannon
- lightning
- list
- loom
- mail
- me
- more
- motd
- msgtoggle
- mute
- near
- nick
- nuke
- tpoffline
- pay
- paytoggle
- payconfirmtoggle
- ping
- playtime
- potion
- powertool
- powertoollist
- powertooltoggle
- ptime
- pweather
- rtoggle
- realname
- recipe
- remove
- renamehome
- repair
- rest
- rules
- seen
- sell
- sethome
- setjail
- settpr
- setwarp
- setworth
- showkit
- editsign
- skull
- smithingtable
- socialspy
- spawner
- spawnmob
- speed
- stonecutter
- sudo
- suicide
- tempban
- tempbanip
- thunder
- time
- togglejail
- top
- tp
- tpa
- tpaall
- tpaccept
- tpahere
- tpall
- tpauto
- tpacancel
- tpdeny
- tphere
- tpo
- tpohere
- tppos
- tpr
- tptoggle
- tree
- unban
- unbanip
- unlimited
- vanish
- warp
- warpinfo
- weather
- whois
- workbench
- world
- worth
auto-afk: -1
auto-afk-timeout: -1
broadcast-afk-message: false
socialspy-commands: []
socialspy-messages: false
socialspy-listen-muted-players: false
starting-balance: 0
command-costs: {}
enabledSigns: []
newbies:
  announce-format: ''
  spawnpoint: default
  kit: ''
spawn-on-join: false
respawn-at-home: true
respawn-at-home-bed: true
respawn-at-anchor: true
respawn-listener-priority: high
delay-motd: -1
