name: Build diagram & Publish Website
on: [push]
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build 🔧
        run: |
          sudo apt-get install graphviz
          pip install diagrams
          cd docs
          python diagram.py
          mkdir build
          mv infra.png build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.8.0
        with:
          branch: gh-pages
          folder: docs/build
